config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # admin

  namespace :admin do
    get 'homes/top' => "homes#top", as: "top"

    resources :customers, only: [:index, :show, :edit, :update]

    patch "orders/update_status" => "orders#update_status", as: "update"
    resources :orders, only: [:show, :update]

    resources :order_details, only: [:update]

    resources :items, only: [:new, :create, :index, :show, :edit, :update]

    resources :genres, only: [:create, :index, :edit, :update]
  end

  # public

  scope module: :public do

    root to: 'homes#top'

    get 'homes/about' => "homes#about", as: "about"

    get 'customers/withdrawal' => "customers#withdrawal", as: "withdrawal"
    get 'customers/information/edit' => "customers#edit", as: "edit"
    patch 'customers/information' => "customers#update", as: "update"
    patch 'customers/status' => "customers#status", as: "status"
    resource :customers, only: [:show]


    resources :addresses, only: [:create, :edit, :update, :index, :destroy]

    post 'orders/order_check' => "orders#order_check", as: "order_check"
    get 'orders/order_finish' => "orders#order_finish", as: "order_finish"
    resources :orders, only: [:new, :create, :show, :index]

    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:create, :index, :update, :destroy]

    resources :items, only: [:show, :index]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_all
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :item_image

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      item_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card:0, transfer:1}
  enum status: {nyuukinmati: 0, nyuukinkakunin: 1, seisakutyuu: 2, hassouzyunbityuu: 3, hassouzumi: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum product_status: {tyakusyuhuka: 0, tyakusyumati: 1, seisakutyuu: 2, seisakukanryou: 3 }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
before_action :authenticate_admin!

  def top
     @orders = Order.all.page(params[:page]).per(10).order("created_at DESC")
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if params[:item][:genre_id].empty?
       redirect_back fallback_location: root_path
    else
    item.save
    redirect_to admin_items_path
    end
  end

  def show
    @item = Item.find(params[:id])
    @total_price = @item.price * 1.08
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end


  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :introduction, :is_active, :item_image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details =@order.order_details.all
  end

  def update
    order = Order.find(params[:id])
    order_details = OrderDetail.where(order_id: params[:id])
    if order.update(order_params)
      order_details.update_all(product_status: 1) if order.status == "nyuukinkakunin"
    end
    redirect_to admin_order_path(order)
  end

  def update_status
    @order = Order.find(params[:id])
    order_details = @order.order_details.find(params[:id])
    order_details.update(order_details_params)
    redirect_to admin_order_path(order)
  end


private
  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private
  def after_sign_in_path_for(namespace_or_scope)
      if namespace_or_scope.is_a?(Admin)
         admin_top_path
      else
         customers_path
      end
  end

  def after_sign_out_path_for(namespace_or_scope)
      if namespace_or_scope == :public
         root_path
      elsif
         namespace_or_scope == :admin
         new_admin_session_path
      else
         root_path
      end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/adimin/order_details_helper.rb
module Adimin::OrderDetailsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container p-3">

    <h4><span style = "background-color: #EEE; padding: 0 20px;">
    <%= @customer.last_name %>
    <%= @customer.first_name %>さんの会員情報編集</span></h4>

        <%= form_with model:@customer, url: admin_customer_path, local:true do |f| %>

          <table style = "margin-left: 30px;">
            <tr>
              <th>
                <p>会員ID</p>
              </th>
              <td valign = "top">
                <p style="padding-left: 30px;"><%= @customer.id %></p>
              </td>
            </tr>
            <tr>
              <th>
               <p>氏名</p>
              </th>
              <td>
                <p style="padding-left: 30px;"><%= f.text_field :last_name, class: "form-control last_name" %></P>
              </td>
              <td>
                <p style="padding-left: 10px;"><%= f.text_field :first_name, class: "form-control first_name" %></p>
              </td>
              </th>
            </tr>
            <tr>
              <th>
               <p>フリガナ</p>
              </th>
              <td>
                <p style="padding-left: 30px;"><%= f.text_field :last_name_kana, class: "form-control last_name_kana" %></p>
              </td>
              <td>
                <p style="padding-left: 10px;"><%= f.text_field :first_name_kana, class: "form-control first_name_kana" %></p>
              </th>
            </tr>
            <tr>
              <th>
               <p>郵便番号</p>
              </th>
              <td>
               <p style="padding-left: 30px;"><%= f.text_field :post_code, class: "form-control post_code" %></p>
              </td>
            </tr>
            <tr>
              <th>
                <p>住所</p>
              </th>
              <td>
               <p style="padding-left: 30px;"><%= f.text_field :address, class: "form-control address" %></p>
              </td>
            </tr>
            <tr>
              <th>
                <p>電話番号</p>
              </th>
              <td>
                <p style="padding-left: 30px;"><%= f.text_field :phone_number, class: "form-control phone_number" %></p>
              </td>
            </tr>
              <th>
                <p>メールアドレス</p>
              </th>
              <td>
                <p style="padding-left: 30px;"><%= f.text_field :email, class: "form-control email" %></p>
              </td>
            <tr>
            </tr>
            <tr>
              <th>
                <p>会員ステータス</p>
              </th>
              <td>
                <p style="padding-left: 30px;">
                  <%= f.radio_button :is_deleted, :false %>
                  <%= f.label :is_deleted, "有効" %>

                  <%= f.radio_button :is_deleted, :true %>
                  <%= f.label :is_deleted, "退会" %></p>
              </td>
            </tr>
            <tr>
              <th></th>
              <td><p style="padding-left: 30px;"><%= f.submit "変更を保存", class: 'btn btn-success' %></p></td>
            </tr>
          </table>
        <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class= "container">
  <div class= "row p-3">
    <h3 style= "background-color:silver">会員一覧</3>
  </div>

  <div class= "row p-3">
    <table class="table">
      <thead>
        <tr class= "table-secondary">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <% @customers.each do |customer| %>
        <td>
          <%= customer.id %>
        </td>
        <td>
          <%= link_to admin_customer_path(customer) do %>
            <%= customer.last_name %><%= customer.first_name %>
          <% end %>
        </td>
        <td>
          <%= customer.email %>
        </td>
        <td>
          <% if customer.is_deleted == false %>
            <p class= "text-success lead">有効</p>
          <% else %>
            <p class= "text-danger lead">退会</p>
          <% end %>
        </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
    
  <div class="row p-3">
    <div class="col-3 mx-auto">
     <%= paginate @customers %>
    </div>
  </div>
  
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row p-3">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <h4><span style = "background-color: #EEE; padding: 0 20px;">
    <%= @customer.last_name %>
    <%= @customer.first_name %>さんの会員詳細</span></h4><br>
    <table style = "width: 100%;">
        <tr>
            <th>
                <p>会員ID</p>
            </th>
            <td>
                <p><%= @customer.id %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>氏名</p>
            </th>
            <td>
                <p><%= @customer.last_name %><%= @customer.first_name %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>フリガナ</p>
            </th>
            <td>
                <p><%= @customer.last_name_kana %><%= @customer.first_name_kana %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>郵便番号</p>
            </th>
            <td>
                <p><%= @customer.post_code %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>住所</p>
            </th>
            <td>
                <p><%= @customer.address %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>電話番号</p>
            </th>
            <td>
                <p><%= @customer.phone_number %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>メールアドレス</p>
            </th>
            <td>
                <p><%= @customer.email %></p>
            </td>
        </tr>

        <tr>
            <th>
                <p>会員ステータス</p>
            </th>
            <td valign = "top">
                <% if @customer.is_deleted %>
                   <p class = text-danger>退会</p>
                <% else %>
                   <p class = text-success>有効</p>
                <% end %>
            </td>
        </tr>

        <tr>
           <td></td>
           <td>
              <p><%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-sm btn-success" %></p>
           </td>
           <td>
              <p><%= link_to "注文履歴一覧を見る", admin_top_path, class:"btn btn-sm btn-primary" %></p>
           </td>
        </tr>
    </table>

  </div>
 </div>
</div>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/show.html.erb
<h1>Customers#show</h1>
<p>Find me in app/views/customers/show.html.erb</p>

app/views/customers/status.html.erb
<h1>Customers#status</h1>
<p>Find me in app/views/customers/status.html.erb</p>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

app/views/customers/withdrawal.html.erb
<h1>Customers#withdrawal</h1>
<p>Find me in app/views/customers/withdrawal.html.erb</p>