config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # admin

  namespace :admin do
    get 'homes/top' => "homes#top", as: "top"

    resources :customers, only: [:index, :show, :edit, :update]

    patch "orders/update_status" => "orders#update_status", as: "update"
    resources :orders, only: [:show, :update]

    resources :order_details, only: [:update]

    resources :items, only: [:new, :create, :index, :show, :edit, :update]

    resources :genres, only: [:create, :index, :edit, :update]
  end

  # public

  scope module: :public do

    root to: 'homes#top'

    get 'homes/about' => "homes#about", as: "about"

    get 'customers/withdrawal' => "customers#withdrawal", as: "withdrawal"
    get 'customers/information/edit' => "customers#edit", as: "edit"
    patch 'customers/information' => "customers#update", as: "update"
    patch 'customers/status' => "customers#status", as: "status"
    resource :customers, only: [:show]


    resources :addresses, only: [:create, :edit, :update, :index, :destroy]

    post 'orders/order_check' => "orders#order_check", as: "order_check"
    get 'orders/order_finish' => "orders#order_finish", as: "order_finish"
    resources :orders, only: [:new, :create, :show, :index]

    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:create, :index, :update, :destroy]

    resources :items, only: [:show, :index]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_all
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :item_image

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      item_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card:0, transfer:1}
  enum status: {nyuukinmati: 0, nyuukinkakunin: 1, seisakutyuu: 2, hassouzyunbityuu: 3, hassouzumi: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum product_status: {tyakusyuhuka: 0, tyakusyumati: 1, seisakutyuu: 2, seisakukanryou: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
before_action :authenticate_admin!

  def top
     @orders = Order.all.page(params[:page]).per(10).order("created_at DESC")
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if params[:item][:genre_id].empty?
       redirect_back fallback_location: root_path
    else
    item.save
    redirect_to admin_items_path
    end
  end

  def show
    @item = Item.find(params[:id])
    @total_price = @item.price * 1.08
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end


  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :introduction, :is_active, :item_image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details =@order.order_details.all
  end

  def update
    order = Order.find(params[:id])
    order_details = OrderDetail.where(order_id: params[:id])
    if order.update(order_params)
      order_details.update_all(product_status: 1) if order.status == "nyuukinkakunin"
    end
    redirect_to admin_order_path(order)
  end

  def update_status
    @order = Order.find(params[:id])
    order_details = @order.order_details.find(params[:id])
    order_details.update(order_details_params)
    redirect_to admin_order_path(order)
  end


private
  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private
  def after_sign_in_path_for(namespace_or_scope)
      if namespace_or_scope.is_a?(Admin)
         admin_top_path
      else
         customers_path
      end
  end

  def after_sign_out_path_for(namespace_or_scope)
      if namespace_or_scope == :public
         root_path
      elsif
         namespace_or_scope == :admin
         new_admin_session_path
      else
         root_path
      end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/adimin/order_details_helper.rb
module Adimin::OrderDetailsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class= "container">
  <div class= "row p-3" style= "background-color:silver">
    <h3>ジャンル編集</h3>
  </div>
  <div class= "row p-3">
    <%= form_with model: @genre, url: admin_genre_path(@genre), local:true do |f| %>
      <div class="form-group">
          <%= f.label "ジャンル名", class: "m-3" %>
          <%= f.text_field :name, class: "m-3" %>
          <%= f.submit"変更を保存", class:"btn btn-success m-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class= "container">
  <div class= "row p-3 bg-light">
    <h3>ジャンル一覧・追加</h3>
  </div>
  <div class= "row p-3">
    <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
      <div class="form-group">
        <%= f.label "ジャンル名" %>
        <%= f.text_field :name,placeholder: "ジャンル名" %>
        <%= f.submit"新規登録", class:"btn btn-success" %>
      </div>
    <% end %>
  </div>

  <div class= "row p-3">
    <table class= "table">
      <thead>
        <tr class="table-secondary">
          <th>ジャンル</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
       <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre), class: 'btn btn-success btn-block' %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container"><br>

    <h4><span style = "background-color: #EEE; margin-left: 70px; padding: 0 20px;">注文履歴詳細</span></h4>

    <table>
         <tr>
           <th>購入者</th>
           <td><%= (@order.customer.last_name + @order.customer.first_name) %></td>
         </tr>
         <tr>
           <th>注文日</th>
           <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
         </tr>
         <tr>
           <th>配送先</th>
           <td>
               〒<%= @order.post_code %><%= @order.address %><br>
               <%= @order.name %>
           </td>
         </tr>
         <tr>
           <th>支払方法</th>
           <td><%= @order.payment_method_i18n %></td>
         </tr>
         <tr>
           <th>注文ステータス</th>
             <td>
             <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
             <%= f.select :status, Order.statuses_i18n.invert %>
             <%= f.submit "更新", class: "btn btn-success btn-sm" %>
             <% end %>
            </td>
         </tr>
    </table>
    <br>

    <div style = "display: flex; align-items: flex-end;">
        <table class = table>
          <thead>
            <tr>
              <th style = "background: #EEE;">商品名</th>
              <th style = "background: #EEE;">単価(税込)</th>
              <th style = "background: #EEE;">数量</th>
              <th style = "background: #EEE;">小計</th>
              <th style = "background: #EEE;">製作ステータス</th>
            </tr>
          </thead>

          <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= (order_detail.price*1.08).ceil.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td><%= (order_detail.price*order_detail.amount).to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <%= f.select :product_status, OrderDetail.product_statuses_i18n.invert %>
                <%= f.submit "更新" ,class: "btn btn-success btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      <div style = "width: 90%; margin-left: 50px; margin-bottom: 22px">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @order.total_payment.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_cost.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>請求金額</th>
          <td><%= (@order.total_payment + @order.shipping_cost).to_s(:delimited) %></td>
        </tr>
      </table>
      </div>
    </div>

</div>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/order_check.html.erb
<h1>Orders#order_check</h1>
<p>Find me in app/views/orders/order_check.html.erb</p>

app/views/orders/order_finish.html.erb
<h1>Orders#order_finish</h1>
<p>Find me in app/views/orders/order_finish.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>