config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # admin

  namespace :admin do
    get 'homes/top' => "homes#top", as: "top"

    resources :customers, only: [:index, :show, :edit, :update]

    patch "orders/update_status" => "orders#update_status", as: "update"
    resources :orders, only: [:show, :update]

    resources :order_details, only: [:update]

    resources :items, only: [:new, :create, :index, :show, :edit, :update]

    resources :genres, only: [:create, :index, :edit, :update]
  end

  # public

  scope module: :public do

    root to: 'homes#top'

    get 'homes/about' => "homes#about", as: "about"

    get 'customers/withdrawal' => "customers#withdrawal", as: "withdrawal"
    get 'customers/information/edit' => "customers#edit", as: "edit"
    patch 'customers/information' => "customers#update", as: "update"
    patch 'customers/status' => "customers#status", as: "status"
    resource :customers, only: [:show]


    resources :addresses, only: [:create, :edit, :update, :index, :destroy]

    post 'orders/order_check' => "orders#order_check", as: "order_check"
    get 'orders/order_finish' => "orders#order_finish", as: "order_finish"
    resources :orders, only: [:new, :create, :show, :index]

    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:create, :index, :update, :destroy]

    resources :items, only: [:show, :index]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_all
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :item_image

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      item_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card:0, transfer:1}
  enum status: {nyuukinmati: 0, nyuukinkakunin: 1, seisakutyuu: 2, hassouzyunbityuu: 3, hassouzumi: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum product_status: {tyakusyuhuka: 0, tyakusyumati: 1, seisakutyuu: 2, seisakukanryou: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
before_action :authenticate_admin!

  def top
     @orders = Order.all.page(params[:page]).per(10).order("created_at DESC")
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if params[:item][:genre_id].empty?
       redirect_back fallback_location: root_path
    else
    item.save
    redirect_to admin_items_path
    end
  end

  def show
    @item = Item.find(params[:id])
    @total_price = @item.price * 1.08
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end


  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :introduction, :is_active, :item_image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private
  def after_sign_in_path_for(namespace_or_scope)
      if namespace_or_scope.is_a?(Admin)
         admin_top_path
      else
         customers_path
      end
  end

  def after_sign_out_path_for(namespace_or_scope)
      if namespace_or_scope == :public
         root_path
      elsif
         namespace_or_scope == :admin
         new_admin_session_path
      else
         root_path
      end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <!--ヘッダーのナビゲーションメニューとカラースキームの指定-->
  <!--画面幅によってナビゲーションを折りたたむ-->
  <nav class="navbar navbar-expand-lg" style="background-color: #DAC3B2;">
  <div class="container">

  <!--長野ケーキ（ロゴ）：トップに戻るルートパスを設定-->
  <%= link_to root_path do %>
    <%= image_tag 'nagano_physique.PNG', alt: 'logo用画像', size: '180x80' %>
  <% end %>

  <!--ハンバーガーメニューへの切り替え-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon", style="color:#fff;"><i class= "fas fa-list"></i></span>
  </button>

  <!--ナビゲーションが閉じたり開いたりする動作-->
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">

    <% if customer_signed_in? %>
      <div style="margin: 10px; color: #fff;">ようこそ<%= current_customer.last_name + current_customer.first_name %>さん！</div>
        <li style="margin: 10px;">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "カート", cart_items_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "マイページ", customers_path, class: "btn btn-outline-light btn-sm" %>
        </li>

    <% elsif admin_signed_in? %>
        <li style="margin: 10px;">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "注文履歴一覧", admin_top_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-light btn-sm" %>
        </li>

    <% else %>
        <li style="margin: 10px;">
          <%=  link_to "ログイン", customer_session_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-light btn-sm" %>
        </li>
        <li style="margin: 10px;">
          <%= link_to "About", about_path, class: "btn btn-outline-light btn-sm" %>
        </li>
    <% end %>
  </div>

    <div class="search-box" style="margin: 10px;">
      <input type="text" class="form-control" placeholder="Search">
    </div>
    <i class="fas fa-search" style="color:#fff;"></i>
    </div>
</nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer class="footer" style="background-color: #DAC3B2; padding: 10px;">
    <div class="container">
    <div class="row">
      <div class="mx-auto">
        <i class="fab fa-line" style="font-size: 2em; margin: 10px; color: #453232;"></i>
        <i class="fab fa-twitter-square" style="font-size: 2em; margin: 10px; color: #453232;"></i>
        <i class="fab fa-instagram" style="font-size: 2em; margin: 10px; color: #453232;"></i>
        <i class="fab fa-youtube-square" style="font-size: 2em; margin: 10px; color: #453232;"></i>
        <p style="color: #fff; text-align: center;">CopyRight team-Physique</p>
      </div>
    </div>
  </div>
  </footer>

</html>